# prometheus-rules.yaml 예시
groups:
  - name: example-rules
    rules:
      - alert: HostHighCpuLoad
        expr: node_cpu_seconds_total / count(node_cpu_seconds_total) * 100 > 80
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "CPU 사용량 높음 (인스턴스: {{ $labels.instance }})"
          description: "CPU 사용량이 5분 동안 80%를 초과했습니다."
