cat <<EOF > stress-test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: stress-test
spec:
  containers:
  - name: stress
    image: vish/stress
    args: ["--cpus", "1", "--mem-total", "200M", "--mem-alloc-size", "100M", "--mem-alloc-sleep", "1s"]
EOF